name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  SERVER_TAG: ghcr.io/kennethkongiw/openvsx-server
  WEBUI_TAG: ghcr.io/kennethkongiw/openvsx-webui

jobs:
  build:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Install Yarn
      run: |
        corepack enable
        corepack prepare yarn@stable --activate
    - uses: actions/checkout@v4
    - name: Set Image Version
      run: echo "IMAGE_VERSION=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
    - name: Build CLI
      run: yarn --cwd cli
    - name: Build Web UI Image
      run: docker build -t $WEBUI_TAG:$IMAGE_VERSION webui
    - name: Get all changed server files
      id: changed_server_files
      uses: tj-actions/changed-files@v46.0.5
      with:
        files: server/**
    - name: Run Server Tests
      if: steps.changed_server_files.outputs.any_changed == 'true'
      run: server/gradlew --no-daemon -p server check
      env:
        DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_API_TOKEN }}
    - name: Build Server Image
      run: docker build -t $SERVER_TAG:$IMAGE_VERSION server --secret id=dv-key,env=DEVELOCITY_ACCESS_KEY
      env:
        DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_API_TOKEN }}
    - name: Push Docker Images
      run: |
        echo ${{ secrets.BOT_ACCESS_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker push $SERVER_TAG:$IMAGE_VERSION
        docker push $WEBUI_TAG:$IMAGE_VERSION
      if: github.repository == 'kennethkongiw/openvsx' && github.ref == 'refs/heads/develop'
    - name: Save PR number to file
      if: github.event_name == 'pull_request'
      run: echo ${{ github.event.number }} > PR_NUMBER.txt
    - name: Archive PR number
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: PR_NUMBER
        path: PR_NUMBER.txt
